#!/bin/bash

echo "*** downloading toggle script and place it in correct folder"
cd "/Library/Scripts" && curl -LO https://github.com/jsphweid/hotkey-grid/raw/finale-mac/scripts/osxCapsToggle/toggleGridAsScript.scpt
echo "end"